In [1]:
import numpy as np
import sys

# THE BASIC

In [2]:
a = np.array([1,2,3], dtype='int8')
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])

#print Matrix
print(a)
print(b)

#Get Dimension
print('Dimension', a.ndim)

# Get type/size
print("type", b.dtype)
print("type", a.dtype)

[1 2 3]
[[1. 2. 3.]
 [4. 5. 6.]]
Dimension 1
type float64
type int8


In [6]:
# Get size
a.itemsize

1

In [7]:
b.itemsize

8

In [11]:
# Get total size
a.nbytes

3

In [10]:
b.nbytes

48

# Accessing/Changing specific element, rows, column, etc

In [3]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [4]:
# Get a specific element 
a[1,5]

13

In [5]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [16]:
a[:,5]

array([ 6, 13])

In [19]:
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [6]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [7]:
a[1,5] = 20
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


# 3-D Examples

In [8]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
# Get specific element (work outside in)
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [28]:
b[0,1,1]

4

In [30]:
# replace
b[:,1,:]

array([[3, 4],
       [7, 8]])

# Initializing Different Types of Arrays

In [34]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
# All onces Matrix

np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [38]:
# Any other matrix
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [40]:
np.full((6,6),55)

array([[55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55]])

In [10]:
# Any other number (full like)
np.full_like(a.shape, 4)

array([4, 4])

In [12]:
# Random decimal number
np.random.rand(4,2)

array([[0.92233489, 0.42888881],
       [0.09983761, 0.83055202],
       [0.25481597, 0.91450816],
       [0.51516997, 0.71758543]])

In [18]:
# Random Integer value
np.random.randint(7, size=(3,3))

array([[6, 6, 3],
       [6, 0, 6],
       [1, 4, 3]])

In [20]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
# Repeart an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


# Mathematics

In [29]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [30]:
a+2

array([3, 4, 5, 6])

In [31]:
a-2

array([-1,  0,  1,  2])

In [32]:
a*2

array([2, 4, 6, 8])

In [33]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [34]:
b = np.array([1,0,1,0])

In [35]:
a+b

array([2, 2, 4, 4])

In [36]:
a-b

array([0, 2, 2, 4])

In [37]:
a**b

array([1, 1, 3, 1], dtype=int32)

In [38]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [39]:
np.cos(b)

array([0.54030231, 1.        , 0.54030231, 1.        ])

In [40]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [41]:
np.cosh(b)

array([1.54308063, 1.        , 1.54308063, 1.        ])

# Linear Algebra

In [47]:
a = np.full((2,3),2)
print(a)

b = np.ones((3,2))
print(b)

np.matmul(a,b)

[[2 2 2]
 [2 2 2]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


array([[6., 6.],
       [6., 6.]])

In [51]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/refernce/routines.linalg.hmtl)

# Determinant
# Trace
# Singular vector Decomposition
# EigenValues
# Matrix Norm
# Inverse
# Etc

# statistics

In [55]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
np.max(stats, axis=0)

array([4, 5, 6])

In [57]:
np.min(stats)

1

In [60]:
np.sum(stats, axis=0)

array([5, 7, 9])

# Reorganizing array

In [61]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
after(a)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
# Vertical stacking vector
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.ones((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])